"""Synthetic ground-truth tests for the Hawkes toolkit.

The simulator, the exponential-kernel MLE and the count-variance branching
estimator are trustworthy only insofar as they recover known parameters on
data generated by the simulator itself (and, for the trap test, on data
from a process that is deliberately not Hawkes).
"""
from __future__ import annotations

import numpy as np
import pytest

from microstructure.estimators.hawkes import (
    MAX_PIECEWISE_BLOCKS,
    HawkesFit,
    MultiExpFit,
    PiecewiseMuFit,
    _drift_verdict,
    _nelder_mead,
    baseline_drift_control,
    branching_count_variance,
    branching_ratio_sensitivity,
    fit_hawkes_exp,
    fit_hawkes_exp_piecewise_mu,
    fit_hawkes_multiexp,
    hawkes_loglik,
    hawkes_multiexp_loglik,
    hawkes_piecewise_mu_loglik,
    simulate_hawkes_exp,
    simulate_hawkes_multiexp,
    simulate_seasonal_hawkes_exp,
    spurious_delta21_null,
)

# ---------------------------------------------------------------------------
# Group 0: Nelder-Mead sanity check on a known quadratic (test the optimizer
# itself before trusting it to fit anything statistical).
# ---------------------------------------------------------------------------


def test_nelder_mead_recovers_quadratic_minimum():
    # f(x, y) = (x - 3)^2 + (y + 2)^2 + 7, minimum at (3, -2), f_min = 7.
    def f(p: np.ndarray) -> float:
        return float((p[0] - 3.0) ** 2 + (p[1] + 2.0) ** 2 + 7.0)

    x0 = np.array([0.0, 0.0])
    best_x, best_f, converged = _nelder_mead(f, x0, max_iter=500)
    assert converged
    assert abs(best_x[0] - 3.0) < 1e-3
    assert abs(best_x[1] - (-2.0)) < 1e-3
    assert abs(best_f - 7.0) < 1e-5


def test_nelder_mead_handles_rosenbrock_like_valley():
    # A harder, curved-valley function: minimum at (1, 1), f_min = 0.
    def f(p: np.ndarray) -> float:
        x, y = p
        return float(100.0 * (y - x**2) ** 2 + (1.0 - x) ** 2)

    x0 = np.array([-1.0, 1.5])
    best_x, best_f, _converged = _nelder_mead(f, x0, max_iter=2000)
    assert best_f < 1e-3
    assert abs(best_x[0] - 1.0) < 0.05
    assert abs(best_x[1] - 1.0) < 0.05


# ---------------------------------------------------------------------------
# Group 0b: log-likelihood formula verified against numerical integration
# of the intensity on a tiny hand-checkable case.
# ---------------------------------------------------------------------------


def test_loglik_matches_numerical_intensity_integration():
    """Verify Σ log λ(t_i) − ∫λ(t)dt against brute-force numerical intensity.

    Uses 10 fixed event times (not simulated) so the check is independent
    of the simulator. Integrates λ(t) = mu + Σ alpha*beta*exp(-beta(t-t_i))
    with a fine trapezoid rule over [0, T] and compares to the closed-form
    recursion used in hawkes_loglik.
    """
    times = np.array([1.0, 1.3, 2.1, 2.15, 3.0, 4.4, 4.5, 4.55, 6.0, 8.0])
    t_end = 10.0
    mu, alpha, beta = 0.3, 0.5, 1.5

    ll_closed = hawkes_loglik(times, t_end, mu, alpha, beta)

    # Brute-force: Σ log λ(t_i^-) exactly (no integration needed for the
    # sum term — λ just before each event, using only prior events).
    log_sum = 0.0
    for i, ti in enumerate(times):
        prior = times[:i]
        excitation = np.sum(alpha * beta * np.exp(-beta * (ti - prior))) if i > 0 else 0.0
        log_sum += np.log(mu + excitation)

    # Numerically integrate the compensator ∫_0^T λ(t) dt via fine trapezoid.
    grid = np.linspace(0.0, t_end, 2_000_000)
    excitation_grid = np.zeros_like(grid)
    for ti in times:
        mask = grid > ti
        excitation_grid[mask] += alpha * beta * np.exp(-beta * (grid[mask] - ti))
    lam_grid = mu + excitation_grid
    compensator_numeric = np.trapezoid(lam_grid, grid)

    ll_numeric = log_sum - compensator_numeric

    assert abs(ll_closed - ll_numeric) < 1e-3, (ll_closed, ll_numeric)


# ---------------------------------------------------------------------------
# Group 0c: simulate_hawkes_exp must reject explosive/invalid parameters at
# entry rather than hang. alpha >= 1 makes the branching ratio >= 1, so the
# expected number of descendants per event diverges and the thinning loop
# never reaches t_end in finite time/memory (alpha=1.5 never terminates
# without this guard).
# ---------------------------------------------------------------------------


def test_simulate_rejects_alpha_at_or_above_one():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 1.0, 2.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 1.5, 2.0, 1000.0, seed=1)


def test_simulate_rejects_negative_alpha():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, -0.1, 2.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_mu():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.0, 0.4, 2.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(-0.1, 0.4, 2.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_beta():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 0.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, -1.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_t_end():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 2.0, 0.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 2.0, -100.0, seed=1)


# ---------------------------------------------------------------------------
# Group 1: simulate -> fit round trip across 3 seeds.
# ---------------------------------------------------------------------------

TRUE_MU, TRUE_ALPHA, TRUE_BETA = 0.5, 0.4, 2.0
T_END = 200_000.0
FIT_SUBSAMPLE_T = 100_000.0  # fit on the first 100k seconds of events


def _simulate_and_fit(seed: int) -> tuple[np.ndarray, HawkesFit]:
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    # Fit on the first FIT_SUBSAMPLE_T seconds only: full sims are 150-300k
    # events, and fitting about half keeps the suite fast at a realistic size.
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    return times, fit


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_mle_recovers_known_parameters(seed):
    _, fit = _simulate_and_fit(seed)
    assert fit.converged
    assert abs(fit.alpha - TRUE_ALPHA) < 0.03, f"seed={seed} alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.05, f"seed={seed} mu={fit.mu}"
    assert abs(fit.beta - TRUE_BETA) / TRUE_BETA < 0.20, f"seed={seed} beta={fit.beta}"


def test_mle_alpha_stable_across_seeds():
    alphas = []
    for seed in (7, 8, 9):
        _, fit = _simulate_and_fit(seed)
        alphas.append(fit.alpha)
    sd = float(np.std(alphas, ddof=1))
    assert sd < 0.02, f"alphas={alphas} sd={sd}"


# ---------------------------------------------------------------------------
# Group 2: count-variance estimator on the same simulations.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_count_variance_recovers_branching_ratio(seed):
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - TRUE_ALPHA) < 0.05, f"seed={seed} n_hat={n_hat}"


def test_count_variance_guards_too_few_windows():
    times = np.array([1.0, 2.0, 3.0])
    with pytest.raises(ValueError):
        branching_count_variance(times, window=1.0, t_end=3.0)


def test_count_variance_guards_zero_variance():
    # Perfectly regular spacing (one event every 1.0s) with window=10.0
    # puts exactly 10 events in every non-overlapping window -> var == 0.
    times = np.arange(0.0, 10_000.0, 1.0)
    with pytest.raises(ValueError):
        branching_count_variance(times, window=10.0, t_end=10_000.0)


# ---------------------------------------------------------------------------
# Group 3: near-critical regime (alpha=0.85) — wider tolerances, documented.
# ---------------------------------------------------------------------------

NEAR_CRITICAL_ALPHA = 0.85


def test_near_critical_mle_recovers_within_widened_tolerance():
    """Near n=1, mu/alpha are weakly identified locally, so tolerances are wider
    than in the n=0.4 case.
    """
    times = simulate_hawkes_exp(TRUE_MU, NEAR_CRITICAL_ALPHA, TRUE_BETA, T_END, seed=11)
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert abs(fit.alpha - NEAR_CRITICAL_ALPHA) < 0.08, f"alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.15, f"mu={fit.mu}"

    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - NEAR_CRITICAL_ALPHA) < 0.12, f"n_hat={n_hat}"


# ---------------------------------------------------------------------------
# Group 4: Poisson refutation test (the Filimonov-Sornette trap).
# ---------------------------------------------------------------------------


def test_poisson_refutation_both_estimators_report_near_zero():
    """A pure Poisson stream (alpha=0) must NOT look self-exciting.

    Only fit.alpha is asserted, not fit.beta: at alpha=0 the excitation term
    alpha*beta*R_i vanishes regardless of beta, so the likelihood is flat in
    beta and the fitted value carries no information.
    """
    rng = np.random.default_rng(21)
    rate = 1.0
    t_end = 200_000.0
    n_expected = int(rate * t_end * 1.05)
    gaps = rng.exponential(1.0 / rate, size=n_expected)
    times = np.cumsum(gaps)
    times = times[times <= t_end]

    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.alpha < 0.05, f"fitted alpha={fit.alpha} on pure Poisson"

    n_hat = branching_count_variance(times, window=500.0, t_end=t_end)
    assert n_hat < 0.05, f"count-variance n_hat={n_hat} on pure Poisson"


def test_regime_switching_poisson_produces_spurious_endogeneity_trap():
    """The Filimonov & Sornette (2015) trap: a near-critical n̂ can appear with
    no self-excitation at all. A regime-switching Poisson process (a rate
    alternating between a low and a high value on a fixed clock) gives a
    spurious positive branching-ratio estimate, because clustering from rate
    non-stationarity is indistinguishable, to a likelihood fit and to a
    count-mean/variance test, from clustering from self-excitation.

    This is why the baseline mu(t) must be deseasonalized before testing for
    endogeneity. The asserted n_hat > 0.2 (count-variance) and fitted
    alpha > 0.5 (MLE) show the spurious effect is large in both estimators,
    not rounding error.
    """
    rng = np.random.default_rng(22)
    low_rate, high_rate = 0.5, 2.0
    regime_len = 5000.0
    t_end = 200_000.0

    times: list[float] = []
    t = 0.0
    regime_start = 0.0
    is_low = True
    while regime_start < t_end:
        rate = low_rate if is_low else high_rate
        regime_end = min(regime_start + regime_len, t_end)
        t = regime_start
        while True:
            t += rng.exponential(1.0 / rate)
            if t >= regime_end:
                break
            times.append(t)
        regime_start = regime_end
        is_low = not is_low

    times_arr = np.asarray(times, dtype=np.float64)

    n_hat = branching_count_variance(times_arr, window=500.0, t_end=t_end)
    assert n_hat > 0.2, (
        f"expected the regime-switching trap to produce spurious n_hat > 0.2, "
        f"got {n_hat}"
    )

    fit_times = times_arr[times_arr <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.alpha > 0.5, (
        f"expected the regime-switching trap to also fool the MLE with "
        f"fitted alpha > 0.5, got {fit.alpha}"
    )


# ---------------------------------------------------------------------------
# Group 5: simulate_seasonal_hawkes_exp, a Hawkes process with a periodic,
# piecewise-constant baseline rate, for testing business-time rescaling
# against a real generative model rather than a post-hoc-thinned one.
# ---------------------------------------------------------------------------


def test_simulate_seasonal_rejects_invalid_parameters():
    flat_shape = np.ones(48)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.0, 0.4, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(-0.1, 0.4, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, -0.1, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 1.0, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 0.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 0.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, np.array([]), seed=1)
    with pytest.raises(ValueError):
        # non-positive entry in shape
        bad_shape = np.ones(48)
        bad_shape[3] = 0.0
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, bad_shape, seed=1)
    with pytest.raises(ValueError):
        # non-finite entry in shape
        bad_shape = np.ones(48)
        bad_shape[3] = np.nan
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, bad_shape, seed=1)


def test_simulate_seasonal_stationary_shape_recovers_known_parameters():
    """Sanity: a flat (mean-1) shape gives no seasonal confound, so a fit on
    the seasonal simulator's output should recover parameters just as well
    as the unseasonal simulator does (Group 1's tolerances)."""
    flat_shape = np.ones(48)
    times = simulate_seasonal_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, flat_shape, seed=7)
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.converged
    assert abs(fit.alpha - TRUE_ALPHA) < 0.05, f"alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.08, f"mu={fit.mu}"


def test_simulate_seasonal_reduces_to_unseasonal_statistically():
    """With shape≡1 the seasonal simulator should match `simulate_hawkes_exp`
    statistically (event count and fitted parameters), though not in exact
    event times, since the acceptance draws differ."""
    flat_shape = np.ones(48)
    seasonal_times = simulate_seasonal_hawkes_exp(
        TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, flat_shape, seed=7
    )
    unseasonal_times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=7)

    # Event counts should be close; the tolerance is generous because the
    # seeds drive different acceptance sequences.
    rel_diff = abs(seasonal_times.size - unseasonal_times.size) / unseasonal_times.size
    assert rel_diff < 0.05, (
        f"seasonal n={seasonal_times.size} vs unseasonal n={unseasonal_times.size}, "
        f"rel_diff={rel_diff}"
    )

    fit_times = seasonal_times[seasonal_times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert abs(fit.alpha - TRUE_ALPHA) < 0.05, f"alpha={fit.alpha}"


# ---------------------------------------------------------------------------
# Group 6: sum-of-exponentials Hawkes kernel (K-sensitivity of n̂).
#
# A K=1 fit on data from a 2-timescale kernel should underestimate the true
# branching ratio, a K=2 fit should recover it, and a K=3 fit
# (over-parameterized) should stay in the right ballpark without blowing up.
# This probes the project's 41/41-symbol exp-MLE vs count-variance
# disagreement.
#
# Caveat tested at the end of this group
# (`test_seasonal_baseline_confound_mimics_long_memory`): the K=1->K=2 n̂ rise
# and slow-component signature used above is not unique to long memory.
# Residual baseline non-stationarity (imperfect deseasonalization, regime
# changes) produces the same signature in a process with no long memory, so
# n̂(K) alone cannot separate the two. See that test and
# `fit_hawkes_multiexp` for the diagnostic (compare the slow component's
# timescale to the deseasonalization bin width / fit-window length) and the
# control (re-fit K=1 with a block-wise-constant baseline).
# ---------------------------------------------------------------------------

# Planted 2-exponential kernel: alpha=(0.25, 0.35) [n=0.6], beta=(5, 0.2)
# (one fast component, timescale 1/5=0.2, and one slow component, timescale
# 1/0.2=5, a 25x separation).
PLANTED_MU = 0.5
PLANTED_ALPHAS = np.array([0.25, 0.35])
PLANTED_BETAS = np.array([5.0, 0.2])
PLANTED_N = float(PLANTED_ALPHAS.sum())  # 0.6
# mean_rate ~ mu/(1-n) = 0.5/0.4 = 1.25/unit time; t_end=48_000 gives ~60k events.
PLANTED_T_END = 48_000.0


def test_multiexp_k1_matches_fit_hawkes_exp():
    """K=1 must reproduce fit_hawkes_exp on the same data.

    With one component the alpha-logit softmax reduces to the logistic map
    fit_hawkes_exp uses, so both optimizers search the same likelihood surface
    and should land on the same optimum.
    """
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=7)
    fit_times = times[times <= FIT_SUBSAMPLE_T]

    single = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    multi = fit_hawkes_multiexp(fit_times, FIT_SUBSAMPLE_T, K=1)

    assert multi.K == 1
    assert multi.alphas.shape == (1,)
    assert multi.betas.shape == (1,)
    # The two fits run independent Nelder-Mead searches (different simplex
    # paths and multi-start beta seeds) over the same likelihood, so they agree
    # only up to each optimizer's tol=1e-6 stopping criterion. Measured here:
    # loglik ~1e-7, mu/alpha ~1e-6/1e-7, beta (the flattest direction) ~3e-5.
    # The tolerances (loglik 1e-5, mu/alpha 1e-5, beta 1e-4) leave headroom
    # while still showing the two code paths compute the same thing.
    assert abs(multi.mu - single.mu) < 1e-5, (multi.mu, single.mu)
    assert abs(multi.alphas[0] - single.alpha) < 1e-5, (multi.alphas[0], single.alpha)
    assert abs(multi.betas[0] - single.beta) < 1e-4, (multi.betas[0], single.beta)
    assert abs(multi.n - single.alpha) < 1e-5
    assert abs(multi.loglik - single.loglik) < 1e-5, (multi.loglik, single.loglik)


def test_simulate_multiexp_rejects_invalid_parameters():
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(0.0, PLANTED_ALPHAS, PLANTED_BETAS, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(-0.1, PLANTED_ALPHAS, PLANTED_BETAS, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(0.5, PLANTED_ALPHAS, PLANTED_BETAS, 0.0, seed=1)
    with pytest.raises(ValueError):
        # mismatched lengths
        simulate_hawkes_multiexp(0.5, np.array([0.3, 0.3]), np.array([1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # negative beta
        simulate_hawkes_multiexp(0.5, np.array([0.3]), np.array([-1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # negative alpha
        simulate_hawkes_multiexp(0.5, np.array([-0.1]), np.array([1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # n = sum(alphas) >= 1: explosive
        simulate_hawkes_multiexp(0.5, np.array([0.6, 0.5]), np.array([5.0, 0.2]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # empty alphas/betas
        simulate_hawkes_multiexp(0.5, np.array([]), np.array([]), 1000.0, seed=1)


def test_fit_multiexp_rejects_invalid_k_and_betas_init():
    times = np.array([1.0, 2.0, 3.0, 4.0])
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=0)
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=2, betas_init=np.array([1.0]))  # wrong length
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=1, betas_init=np.array([-1.0]))  # non-positive
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(np.array([1.0]), 10.0, K=1)  # < 2 events


def _simulate_planted_2exp(seed: int) -> np.ndarray:
    return simulate_hawkes_multiexp(
        PLANTED_MU, PLANTED_ALPHAS, PLANTED_BETAS, PLANTED_T_END, seed=seed
    )


@pytest.fixture(scope="module")
def planted_sensitivity() -> dict[int, MultiExpFit]:
    """Fit K=1,2,3 once on the planted 2-exp dataset (via
    `branching_ratio_sensitivity`) and share it across the K-sensitivity tests;
    refitting per test would multiply the K=3-dominated runtime."""
    times = _simulate_planted_2exp(seed=42)
    return branching_ratio_sensitivity(times, PLANTED_T_END, Ks=(1, 2, 3))


def test_multiexp_k1_underestimates_planted_two_timescale_kernel(planted_sensitivity):
    """K=1 underestimates n on 2-timescale data.

    True n=0.6 (alpha=(0.25,0.35), beta=(5,0.2), timescales 25x apart). A
    single exponential cannot represent both timescales at once and
    underestimates the total kernel mass by over-weighting the fast
    component's decay. Asserts n̂₁ < 0.6 - 0.03.
    """
    fit_k1 = planted_sensitivity[1]

    assert fit_k1.n < PLANTED_N - 0.03, (
        f"expected K=1 to demonstrably underestimate n (< {PLANTED_N - 0.03}), "
        f"got n_hat={fit_k1.n}"
    )


def test_multiexp_k2_recovers_planted_two_timescale_kernel(planted_sensitivity):
    """K=2 (matching the true kernel's component count) recovers n within ±0.06."""
    fit_k2 = planted_sensitivity[2]

    assert fit_k2.converged
    assert abs(fit_k2.n - PLANTED_N) < 0.06, f"n_hat={fit_k2.n}, true n={PLANTED_N}"


def test_multiexp_k3_on_two_exp_data_does_not_blow_up(planted_sensitivity):
    """K=3 (over-parameterized relative to the true K=2 kernel) should still
    land in the right ballpark (±0.08) and converge: the extra component should
    not run away to a degenerate or explosive solution (see the identifiability
    caveat in fit_hawkes_multiexp)."""
    fit_k3 = planted_sensitivity[3]

    assert fit_k3.converged
    assert abs(fit_k3.n - PLANTED_N) < 0.08, f"n_hat={fit_k3.n}, true n={PLANTED_N}"
    assert fit_k3.n < 1.0
    assert np.all(np.isfinite(fit_k3.alphas))
    assert np.all(np.isfinite(fit_k3.betas))


def test_multiexp_loglik_rejects_invalid_parameters():
    """Guard: mu<=0, any beta<=0, any alpha<0, or n=sum(alpha)>=1 -> -inf."""
    from microstructure.estimators.hawkes import hawkes_multiexp_loglik

    times = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    t_end = 10.0
    good_alphas = np.array([0.2, 0.2])
    good_betas = np.array([5.0, 0.5])

    assert hawkes_multiexp_loglik(times, t_end, 0.0, good_alphas, good_betas) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, -0.1, good_alphas, good_betas) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, 0.3, good_alphas, np.array([5.0, -0.5])) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, 0.3, np.array([-0.1, 0.2]), good_betas) == -np.inf
    assert (
        hawkes_multiexp_loglik(times, t_end, 0.3, np.array([0.6, 0.5]), good_betas) == -np.inf
    )  # n=1.1 >= 1


def test_branching_ratio_sensitivity_returns_fit_per_k(planted_sensitivity):
    """branching_ratio_sensitivity returns one MultiExpFit per requested K,
    keyed by K. Reuses the `planted_sensitivity` fixture rather than re-fitting."""
    results = planted_sensitivity

    assert set(results.keys()) == {1, 2, 3}
    assert isinstance(results[1], MultiExpFit)
    assert results[1].K == 1
    assert results[2].K == 2
    assert results[3].K == 3
    # The K-sensitivity finding also holds through the wrapper.
    assert results[1].n < results[2].n


def test_seasonal_baseline_confound_mimics_long_memory():
    """Baseline non-stationarity mimics long memory in the K=1 -> K=2 sweep.

    A K=1 -> K=2 rise in n̂ with a slow (small beta) second component is also
    produced by residual baseline non-stationarity that a constant-mu fit
    cannot represent (the Filimonov & Sornette 2015 trap, see
    `test_regime_switching_poisson_produces_spurious_endogeneity_trap`). This
    shows the same confound fools the multi-exponential MLE.

    Ground truth is a single-exponential Hawkes process (n=0.4, beta=2.0, no
    long memory) with a piecewise-constant ±30% baseline wobble:
    `np.tile([0.7, 1.3], 72)` divides the 86400s day into 144 bins of 600s in
    `simulate_seasonal_hawkes_exp`'s convention, and t_end=60_000s covers a bit
    over half a period. K=1 -> K=2 shows n̂1=0.46 -> n̂2=0.83 (a jump above
    0.2) with a spurious near-zero beta component, the same shape as the
    long-memory signature in
    `test_multiexp_k1_underestimates_planted_two_timescale_kernel` and
    `test_multiexp_k2_recovers_planted_two_timescale_kernel`. So n̂(K)
    sensitivity alone cannot separate long memory from a non-constant
    baseline; per `fit_hawkes_multiexp`, that takes (a) comparing the slow
    component's timescale 1/beta_slow with the deseasonalization bin width and
    fit-window length, and (b) the block-wise-constant-mu control.
    """
    shape = np.tile([0.7, 1.3], 72)
    t_end = 60_000.0
    times = simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, t_end, shape, seed=5)

    fit_k1 = fit_hawkes_multiexp(times, t_end, K=1)
    fit_k2 = fit_hawkes_multiexp(times, t_end, K=2)

    assert fit_k2.n - fit_k1.n > 0.2, (
        f"expected the baseline-drift confound to produce a spurious "
        f"n̂ jump > 0.2 (true n=0.4, no long memory at all); got "
        f"n̂1={fit_k1.n}, n̂2={fit_k2.n}"
    )


# ---------------------------------------------------------------------------
# spurious_delta21_null: finite-sample null distribution of Delta21 under a
# true single-exp kernel (no long memory), used to calibrate how large a real
# symbol's Delta21 must be before it is more than sampling noise.
# ---------------------------------------------------------------------------


def test_spurious_delta21_null_median_is_positive_at_small_sample():
    """At 10k events per window, the K=2 fit's extra flexibility absorbs some
    sampling noise into a spurious second component even though the truth is
    K=1: the upward finite-sample bias `spurious_delta21_null` calibrates
    against. n_sims=3 keeps it fast; the median of 3 draws is noisy but was
    consistently positive across seeds (medians of 0.03 and 0.01-0.02, never
    negative or exactly zero)."""
    null = spurious_delta21_null(10_000, mu=0.5, alpha=0.4, beta=2.0, n_sims=3, seed=123)
    assert null.shape == (3,)
    assert np.median(null) > 0.0, (
        f"expected a positive median Delta21 under a true K=1 process at "
        f"n=10k events (finite-sample bias), got median={np.median(null)}, null={null}"
    )


def test_spurious_delta21_null_shrinks_with_sample_size():
    """The finite-sample bias shrinks as the per-window event count grows. The
    same seed is used at both sizes to isolate the sample-size effect as far as
    3 sims allow."""
    null_small = spurious_delta21_null(10_000, mu=0.5, alpha=0.4, beta=2.0, n_sims=3, seed=123)
    null_large = spurious_delta21_null(40_000, mu=0.5, alpha=0.4, beta=2.0, n_sims=3, seed=123)
    assert np.median(null_large) < np.median(null_small), (
        f"expected the null median to shrink from n=10k to n=40k events/window, "
        f"got median_small={np.median(null_small)} ({null_small}), "
        f"median_large={np.median(null_large)} ({null_large})"
    )


# ---------------------------------------------------------------------------
# Group 7: piecewise-baseline Hawkes control (`fit_hawkes_exp_piecewise_mu`,
# `baseline_drift_control`): re-fit K=1 with a block-wise constant baseline
# instead of a single mu, to test whether a K=1->K=2 rise survives once the
# baseline can vary or vanishes (i.e. was baseline drift absorbed by a
# spurious slow kernel component).
#
# Resolution: a block-wise baseline can only absorb drift slower than the
# block width t_end/n_blocks. The drift fixture below therefore uses a slow
# baseline (4 levels per 86400 s day, i.e. 21600 s per level) against 5000 s
# blocks. A fast wobble (e.g. the 1200 s-period fixture of
# `test_seasonal_baseline_confound_mimics_long_memory`) averages out inside any
# block the <=12-block cap allows and this control cannot resolve it.
# ---------------------------------------------------------------------------


def test_piecewise_mu_loglik_matches_numerical_intensity_integration():
    """Check the block-wise-baseline log-likelihood against brute-force
    numerical integration, as `test_loglik_matches_numerical_intensity_integration`
    does for constant mu. Uses 10 fixed event times with a 4-block baseline
    over t_end=10, so block boundaries fall at non-trivial points relative to
    the events."""
    times = np.array([1.0, 1.3, 2.1, 2.15, 3.0, 4.4, 4.5, 4.55, 6.0, 8.0])
    t_end = 10.0
    n_blocks = 4
    mus = np.array([0.2, 0.4, 0.1, 0.5])
    alpha, beta = 0.5, 1.5
    block_width = t_end / n_blocks

    ll_closed = hawkes_piecewise_mu_loglik(times, t_end, mus, alpha, beta, n_blocks)

    def mu_of_t(t: float) -> float:
        idx = min(int(t // block_width), n_blocks - 1)
        return float(mus[idx])

    log_sum = 0.0
    for i, ti in enumerate(times):
        prior = times[:i]
        excitation = np.sum(alpha * beta * np.exp(-beta * (ti - prior))) if i > 0 else 0.0
        log_sum += np.log(mu_of_t(ti) + excitation)

    grid = np.linspace(0.0, t_end, 2_000_000)
    excitation_grid = np.zeros_like(grid)
    for ti in times:
        mask = grid > ti
        excitation_grid[mask] += alpha * beta * np.exp(-beta * (grid[mask] - ti))
    mu_grid = mus[np.minimum((grid // block_width).astype(int), n_blocks - 1)]
    lam_grid = mu_grid + excitation_grid
    compensator_numeric = np.trapezoid(lam_grid, grid)

    ll_numeric = log_sum - compensator_numeric
    assert abs(ll_closed - ll_numeric) < 1e-3, (ll_closed, ll_numeric)


def test_piecewise_mu_guards_invalid_n_blocks_and_t_end():
    times = np.array([1.0, 2.0, 3.0, 4.0])
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(times, 10.0, n_blocks=0)
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(times, 10.0, n_blocks=-1)
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(times, 10.0, n_blocks=MAX_PIECEWISE_BLOCKS + 1)
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(times, 0.0, n_blocks=4)
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(times, -100.0, n_blocks=4)
    with pytest.raises(ValueError):
        fit_hawkes_exp_piecewise_mu(np.array([1.0]), 10.0, n_blocks=4)  # < 2 events


def test_baseline_drift_control_guards_invalid_n_blocks_and_t_end():
    times = simulate_hawkes_exp(0.5, 0.4, 2.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        baseline_drift_control(times, 0.0, n_blocks=8)
    with pytest.raises(ValueError):
        baseline_drift_control(times, -1.0, n_blocks=8)
    with pytest.raises(ValueError):
        baseline_drift_control(times, 1000.0, n_blocks=0)
    with pytest.raises(ValueError):
        baseline_drift_control(times, 1000.0, n_blocks=MAX_PIECEWISE_BLOCKS + 1)


def test_piecewise_mu_recovers_stationary_process():
    """On a stationary single-exp process (constant mu, no drift), the
    piecewise fit (8 blocks) should recover alpha within +-0.05 of the true 0.4
    and each block's mu within +-25% of the true mu=0.5. With ~5-6k events per
    block, per-block mu has sampling variance even with no non-stationarity."""
    mu, alpha, beta = 0.5, 0.4, 2.0
    t_end = 50_000.0
    times = simulate_hawkes_exp(mu, alpha, beta, t_end, seed=3)

    fit = fit_hawkes_exp_piecewise_mu(times, t_end, n_blocks=8)

    assert isinstance(fit, PiecewiseMuFit)
    assert fit.n_blocks == 8
    assert fit.mus.shape == (8,)
    assert fit.n == fit.alpha
    assert abs(fit.alpha - alpha) < 0.05, f"alpha={fit.alpha}"
    assert np.all(np.abs(fit.mus - mu) / mu < 0.25), f"mus={fit.mus}"


@pytest.mark.parametrize(
    ("k2_rise", "dll_pw", "dll_k2", "n_blocks", "expected"),
    [
        # No material K=2 rise: always inconclusive, even with huge dll_pw.
        (0.1, 500.0, 500.0, 12, "inconclusive"),
        (0.05, 500.0, 500.0, 12, "inconclusive"),
        # n_blocks=12 -> threshold = 19.675/2 = 9.8375.
        (0.3, 9.84, 10.0, 12, "drift"),  # just above threshold, >= 0.5*dll_k2
        (0.3, 9.83, 10.0, 12, "long_memory_candidate"),  # just below threshold
        (0.3, 100.0, 150.0, 12, "drift"),  # above threshold and >= half of dll_k2
        (0.3, 75.0, 150.0, 12, "drift"),  # exactly half of dll_k2
        (0.3, 74.9, 150.0, 12, "inconclusive"),  # significant but < half of dll_k2
        (0.3, 0.0, 100.0, 12, "long_memory_candidate"),
        # n_blocks=2 -> df=1 -> threshold = 3.841/2 = 1.9205.
        (0.3, 1.93, 3.0, 2, "drift"),
        (0.3, 1.92, 3.0, 2, "long_memory_candidate"),
        # K=2 gain itself insignificant (< chi2_0.95(2)/2 = 2.9955): inconclusive,
        # regardless of the block baseline.
        (0.3, 0.0, 2.99, 12, "inconclusive"),
        (0.3, 500.0, 2.0, 12, "inconclusive"),
        (0.3, 0.0, 3.0, 12, "long_memory_candidate"),  # just above the K=2 cutoff
    ],
)
def test_drift_verdict_rule_table(k2_rise, dll_pw, dll_k2, n_blocks, expected):
    assert _drift_verdict(k2_rise, dll_pw, dll_k2, n_blocks) == expected


def test_drift_verdict_rejects_unsupported_n_blocks():
    with pytest.raises(ValueError):
        _drift_verdict(0.3, 1.0, 1.0, 1)
    with pytest.raises(ValueError):
        _drift_verdict(0.3, 1.0, 1.0, MAX_PIECEWISE_BLOCKS + 1)


def test_baseline_drift_control_on_resolvable_drift_is_drift():
    """A single-exponential Hawkes process (n=0.4, beta=2.0, no long memory)
    whose baseline steps between 0.7x and 1.3x every 21600 s (4 levels over a
    86400 s day; `shape = np.tile([0.7, 1.3], 2)`). With n_blocks=12 over
    t_end=60000 s the block width is 5000 s, well below the drift timescale, so
    the block-wise baseline can absorb it. The constant-mu K=1 fit reads
    n ~= 0.46 and K=2 rises far above it with a very slow component on the
    drift; the piecewise fit recovers most of that likelihood and the verdict
    is 'drift'."""
    shape = np.tile([0.7, 1.3], 2)
    t_end = 60_000.0
    times = simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, t_end, shape, seed=5)

    result = baseline_drift_control(times, t_end, n_blocks=12)

    assert set(result) == {
        "n_k1",
        "n_k2",
        "n_k1_piecewise",
        "slow_beta_k2",
        "dll_pw",
        "dll_k2",
        "dll_threshold",
        "verdict",
    }
    k2_rise = result["n_k2"] - result["n_k1"]
    assert k2_rise > 0.1, f"result={result}"
    assert result["dll_pw"] >= -1e-6, f"nesting violated: {result}"
    assert result["dll_pw"] >= result["dll_threshold"], f"result={result}"
    assert result["verdict"] == "drift", f"result={result}"


def test_baseline_drift_control_on_two_exp_process_is_not_drift():
    """On a stationary 2-exponential process (alpha=(0.25,0.35), beta=(5,0.2),
    true n=0.6, the planted-kernel fixture of
    `test_multiexp_k2_recovers_planted_two_timescale_kernel`) K=1
    underestimates and K=2 recovers the true n. There is no baseline drift, so
    the block-wise baseline must not explain the K=2 gain and the verdict must
    not be 'drift'."""
    mu = 0.5
    alphas = np.array([0.25, 0.35])
    betas = np.array([5.0, 0.2])
    t_end = 48_000.0
    true_n = float(alphas.sum())
    times = simulate_hawkes_multiexp(mu, alphas, betas, t_end, seed=42)

    result = baseline_drift_control(times, t_end, n_blocks=8)

    assert result["n_k1"] < 0.5, f"n_k1={result['n_k1']}"
    assert abs(result["n_k2"] - true_n) < 0.06, f"n_k2={result['n_k2']}, true_n={true_n}"
    assert result["dll_pw"] >= -1e-6, f"nesting violated: {result}"
    assert result["verdict"] != "drift", f"result={result}"
    # Not asserted: verdict == "long_memory_candidate". When K=1 is misspecified
    # (true long memory) the block-level LR statistic is inflated, so
    # "inconclusive" is also possible here; on this fixture it is not called drift.
    assert result["dll_pw"] < 0.5 * result["dll_k2"], f"result={result}"


# ---------------------------------------------------------------------------
# Input validation and the non-finite penalty sentinel.
# ---------------------------------------------------------------------------

_GOOD_TIMES = np.array([1.0, 2.0, 3.5, 4.0, 6.0])

_BAD_TIME_INPUTS = {
    "nan_time": (np.array([1.0, np.nan, 3.0, 4.0]), 10.0),
    "inf_time": (np.array([1.0, 2.0, np.inf, 4.0]), 10.0),
    "unsorted": (np.array([1.0, 3.0, 2.0, 4.0]), 10.0),
    "negative_first": (np.array([-0.5, 1.0, 2.0, 4.0]), 10.0),
    "t_end_before_last": (np.array([1.0, 2.0, 3.0, 4.0]), 3.5),
    "nan_t_end": (np.array([1.0, 2.0, 3.0, 4.0]), float("nan")),
    "inf_t_end": (np.array([1.0, 2.0, 3.0, 4.0]), float("inf")),
    "two_dimensional": (np.array([[1.0, 2.0], [3.0, 4.0]]), 10.0),
}

_CALLS = {
    "hawkes_loglik": lambda t, te: hawkes_loglik(t, te, 0.5, 0.3, 2.0),
    "hawkes_multiexp_loglik": lambda t, te: hawkes_multiexp_loglik(
        t, te, 0.5, np.array([0.2, 0.1]), np.array([1.0, 5.0])
    ),
    "hawkes_piecewise_mu_loglik": lambda t, te: hawkes_piecewise_mu_loglik(
        t, te, np.array([0.5, 0.5]), 0.3, 2.0, 2
    ),
    "fit_hawkes_exp": lambda t, te: fit_hawkes_exp(t, te),
    "fit_hawkes_multiexp": lambda t, te: fit_hawkes_multiexp(t, te, K=1),
    "fit_hawkes_exp_piecewise_mu": lambda t, te: fit_hawkes_exp_piecewise_mu(t, te, n_blocks=2),
}


@pytest.mark.parametrize("case", sorted(_BAD_TIME_INPUTS))
@pytest.mark.parametrize("name", sorted(_CALLS))
def test_hawkes_functions_reject_malformed_times(name, case):
    times, t_end = _BAD_TIME_INPUTS[case]
    with pytest.raises(ValueError):
        _CALLS[name](times, t_end)


@pytest.mark.parametrize("name", ["hawkes_loglik", "hawkes_multiexp_loglik"])
def test_loglik_accepts_t_end_equal_to_last_event_and_empty_input(name):
    assert np.isfinite(_CALLS[name](_GOOD_TIMES, float(_GOOD_TIMES[-1])))
    assert np.isfinite(_CALLS[name](np.array([]), 5.0))


def test_nelder_mead_never_reports_convergence_on_the_penalty_sentinel():
    """A flat 1e18 objective has zero simplex spread, which is not convergence."""
    _x, value, converged = _nelder_mead(lambda p: 1e18, np.array([0.0, 1.0]), max_iter=50)
    assert value >= 1e18
    assert converged is False


def test_fits_report_not_converged_when_every_objective_value_is_the_sentinel(monkeypatch):
    from microstructure.estimators import hawkes as hk

    monkeypatch.setattr(hk, "_neg_loglik_transformed", lambda *a, **k: 1e18)
    monkeypatch.setattr(hk, "_neg_multiexp_loglik_transformed", lambda *a, **k: 1e18)
    monkeypatch.setattr(hk, "_neg_piecewise_loglik_transformed", lambda *a, **k: 1e18)
    for fit in (
        fit_hawkes_exp(_GOOD_TIMES, 10.0),
        fit_hawkes_multiexp(_GOOD_TIMES, 10.0, K=1),
        fit_hawkes_exp_piecewise_mu(_GOOD_TIMES, 10.0, n_blocks=2),
    ):
        assert fit.converged is False
        assert fit.loglik == -np.inf
